version: '3'
services:
  inference:
    container_name: inference
    image: claudeperrin228/inference:${INFERENCE_IMAGE_VERSION}
    build: .
    volumes:
      - ${MODELS_LOCAL_PATH}:${MODELS_DOCKER_PATH}
    environment:
      PROMETHEUS_GATEWAY: ${PROMETHEUS_GATEWAY}
      CAMERA_IP: ${CAMERA_IP}
      INFERENCE_PORT: ${INFERENCE_PORT}
      ACTIVE_MODELS: ${ACTIVE_MODELS}
      MODELS_WEIGHT: ${MODELS_WEIGHT}
      MODELS_DOCKER_PATH: ${MODELS_DOCKER_PATH}
      USE_NNPACK: ${USE_NNPACK}
    ports:
      - ${INFERENCE_PORT}:${INFERENCE_PORT}
    command:
      - python 
      - inference.py
